Adding greeting
runewake2/CubeFlyer pull request #38
Opened 2022-08-13 20:33 UTC by cherryis

Added greeting to readme

2022-08-13 20:48 UTC, LocksleyLK requested changes
May want to change REactor to Reactor :)

2022-08-13 20:59 UTC, jimbobbennett requested changes

2022-08-13 20:59 UTC, jimbobbennett commented on game/src/constants.js
> +    'Hello, Open Source at REactor Event'
Reactor, not REactor please.

2022-08-14 00:25 UTC, jimbobbennett approved these changes

2022-08-14 00:25 UTC, merged